### ISSUE TITLE
problem with multiple sheets in a template

### ISSUE THREAD

**Issue by bharathreddy-chipmonk** [ivahaev/go-xlsx-templater#1]
Dear Ivahaev,
When the template has different sheets, the sheets are being created but the data is being reflected in the first sheet only.
I have observed the code and found a mistake/typo which fixes the problem.
I am attaching the new file (attaching xlst.go as xlst.txt as uploading ".go" is not supported). Please check the difference in changes and update the package.

Description of the changes I have made in xlst.go file
Line 31: using j as index instead as i as i was again used inside the loop
Line 33: changing the index of sheet from i to j
Lines 37, 46, 58: changed 0 to j (to use the correct sheet for data updation)

The following 2 lines are changed as for some reason even as setting Width for a Column, xlsx package was not reflecting it. So specifically calling SetColWidth to set the column width.
The following lines are changed regarding this.
Line 131: using index
Added new line (line 140): to call SetColWidth for that particular column

Please update the package. Thanks in advance.
[xlst.txt](https://github.com/ivahaev/go-xlsx-templater/files/373767/xlst.txt)

Thanks and Regards
Bharath

**Comment by ivahaev** [comment]
Thanks for response. Please checkout last commit. I made this changes a couple monthes ago but not commited. Sorry.
 d6358f64186639ff375486a6c545854669e747bc
