### ISSUE TITLE
replacing sub members does not work

### ISSUE THREAD

**Issue by maj-o** [ivahaev/go-xlsx-templater#2]
Hello Ivahaev,

sorry - it was my mistake

Regards maj-o

**Comment by ivahaev** [comment]
:)

**Comment by maj-o** [comment]
Hello Ivahaev,

this has been a user bug, sorry again.
But I have a proposal, please look attachment, changes are marked with
 *NEW

Usage (we needed correct formatting of dates and currencies):



func excel_export(file, source_tempalte, source_data string) error {
var data map[string]interface{}
err := json.Unmarshal([]byte(source_data), &data)
if err == nil {
doc := xlst.New()
doc.SetSpecialCellRenderer(excel_cell_renderer)  // <<<<<<<<<<<<<<<<
err = doc.ReadTemplate(source_tempalte)
if err == nil {
err = doc.Render(data)
if err == nil {
err = doc.Save(file)
}
}
}
return err
}


// this is not perfect and can be made better, but it works >>
func excel_cell_renderer(cell *xlsx.Cell, value string) bool {
if len(cell.NumFmt) > 0 {
if strings.HasPrefix(cell.NumFmt, "#") {
if f, err := strconv.ParseFloat(value, 64); err == nil {
cell.SetFloatWithFormat(f, "#,##0.00")
return true
}
}
if strings.HasPrefix(cell.NumFmt, "mm-") {
if t, err := time.Parse("2006-01-02", value); err == nil {
cell.SetDate(t)
return true
}
}
}
return false
}



with best regards

maj-o



2017-06-14 21:58 GMT+02:00 ivahaev <notifications@github.com>:
